basePath: /
definitions:
  models.LoginInput:
    properties:
      password:
        type: string
      username:
        description: รับค่ามาเป็น "username" แต่เราจะเอาไปเช็คว่าเป็น Email หรือ เบอร์โทร
          ใน Controller
        type: string
    required:
    - password
    - username
    type: object
  models.Product:
    properties:
      barcode:
        description: '[เทคนิค] Barcode ควรเป็น Pointer (*string) เพื่อรองรับค่า NULL'
        example: "885123456789"
        type: string
      category_id:
        example: 2
        type: integer
      cost_price:
        example: 10.5
        type: number
      img_product:
        example: https://image.url/cola.jpg
        type: string
      name:
        example: น้ำอัดลม โคล่า
        type: string
      product_code:
        type: string
      product_id:
        type: integer
      sell_price:
        example: 15
        type: number
      shop_id:
        example: 1
        type: integer
      status:
        example: true
        type: boolean
      stock:
        description: gte=0 คือ มากกว่าหรือเท่ากับ 0
        example: 100
        minimum: 0
        type: integer
      unit:
        example: ขวด
        type: string
    required:
    - category_id
    - cost_price
    - img_product
    - name
    - sell_price
    - shop_id
    - unit
    type: object
  models.RegisterInput:
    properties:
      email:
        type: string
      password:
        example: "123456"
        type: string
      phone:
        type: string
      username:
        example: poder
        type: string
    required:
    - email
    - password
    - phone
    - username
    type: object
  models.Shop:
    properties:
      address:
        example: 123 ถ.สุขุมวิท แขวงคลองเตย เขตคลองเตย กทม 10110
        type: string
      img_qrcode:
        example: https://image.url/qrcode.jpg
        type: string
      img_shop:
        example: https://image.url/homeshop.jpg
        type: string
      name:
        example: จันทร์เพ็ญ
        type: string
      phone:
        example: "0985490445"
        type: string
      pin_code:
        example: "191047"
        type: string
      shop_id:
        type: integer
      user_id:
        example: 1
        type: integer
    required:
    - address
    - name
    - phone
    - pin_code
    - user_id
    type: object
host: localhost:8080
info:
  contact: {}
  description: API สำหรับระบบ EazyStore
  title: EazyStore API
  version: "1.0"
paths:
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: ล็อกอินด้วย Username, Email หรือ เบอร์โทรศัพท์
      parameters:
      - description: ข้อมูลสำหรับ Login
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: เข้าสู่ระบบ (Login)
      tags:
      - Auth
  /api/auth/register:
    post:
      consumes:
      - application/json
      description: ลงทะเบียนผู้ใช้ใหม่เข้าสู่ระบบ
      parameters:
      - description: ข้อมูลสำหรับสมัครสมาชิก
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.RegisterInput'
      produces:
      - application/json
      responses:
        "200":
          description: 'status: success'
          schema:
            type: object
      summary: สมัครสมาชิก
      tags:
      - Auth
  /api/createProduct:
    post:
      consumes:
      - application/json
      description: สร้างรายการสินค้าใหม่ลงในฐานข้อมูล
      parameters:
      - description: ข้อมูลสินค้า
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: เพิ่มสินค้า
      tags:
      - Product
  /api/createShop:
    post:
      consumes:
      - application/json
      description: สร้างร้านค้าใหม่ลงในฐานข้อมูล
      parameters:
      - description: ข้อมูลร้านค้า
        in: body
        name: Shop
        required: true
        schema:
          $ref: '#/definitions/models.Shop'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Shop'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: เพิ่มร้านค้า
      tags:
      - Shop
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
